import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import heroProduct from "@/assets/glowsips.jpg";
import ad1 from "@/assets/glowsips-ad-1.jpg";
import ad2 from "@/assets/glowsips-ad-2.jpg";
import ad3 from "@/assets/glowsips-ad-3.jpg";
import ad4 from "@/assets/glowsips-ad-4.jpg";
import ad5 from "@/assets/glowsips-ad-5.jpg";
import ad6 from "@/assets/glowsips-ad-6.jpg";

const GlowSips = () => {
  const adExperiments = [
    {
      image: ad1,
      feature: "Color-Changing Magic",
      market: "Parents & Kids",
      headline: "Make hydration fun for kids",
      caption: "Family-friendly playful moment positioning",
      ctr: "2.89%",
      cpl: "$2.71"
    },
    {
      image: ad2,
      feature: "Aesthetic Instagram",
      market: "Café Millennials",
      headline: "Your most photogenic drink",
      caption: "Lifestyle and social media appeal",
      ctr: "3.24%",
      cpl: "$2.38"
    },
    {
      image: ad3,
      feature: "Color Transformation",
      market: "Trend Seekers",
      headline: "Watch the magic happen",
      caption: "Product demo showcasing color shift technology",
      ctr: "2.76%",
      cpl: "$2.84"
    },
    {
      image: ad4,
      feature: "Eco-Friendly Reusable",
      market: "Sustainability Advocates",
      headline: "Replace disposables with magic",
      caption: "Environmental angle with natural infusion",
      ctr: "2.41%",
      cpl: "$3.18"
    },
    {
      image: ad5,
      feature: "Flavor Infusion",
      market: "Hydration Enthusiasts",
      headline: "Premium gift for healthy living",
      caption: "Gift set positioning with multiple flavors",
      ctr: "2.58%",
      cpl: "$2.96"
    },
    {
      image: ad6,
      feature: "Family Bonding",
      market: "Health-Conscious Parents",
      headline: "Healthy hydration together",
      caption: "Parent-child connection through wellness",
      ctr: "2.67%",
      cpl: "$2.88"
    }
  ];

  const scrollToResults = () => {
    document.getElementById('experiment-results')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/30">
      {/* Hero Section */}
      <section className="container mx-auto px-6 py-16 md:py-24">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div className="space-y-6">
            <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-foreground">
              GlowSips
            </h1>
            <p className="text-xl text-muted-foreground leading-relaxed">
              A magical reusable straw that changes color when you drink cold liquids and infuses natural flavor drops. Every sip becomes a moment of wonder.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" className="bg-brand hover:bg-brand-hover text-white text-lg px-8 py-6 rounded-full shadow-lg hover:shadow-xl transition-all">
                Fund This Product
              </Button>
              <Button 
                size="lg" 
                variant="outline"
                onClick={scrollToResults}
                className="text-lg px-8 py-6 rounded-full transition-all"
              >
                View Experiment Results
              </Button>
            </div>
          </div>
          <div className="relative">
            <img 
              src={heroProduct} 
              alt="GlowSips Product" 
              className="rounded-3xl shadow-2xl w-full"
            />
            <p className="text-sm text-muted-foreground mt-4 text-center italic">
              Autonomously discovered concept. Image generated by AI.
            </p>
          </div>
        </div>
      </section>

      {/* Product Details */}
      <section className="container mx-auto px-6 py-16 bg-card/50 backdrop-blur">
        <div className="max-w-4xl mx-auto space-y-12">
          <div>
            <h2 className="text-3xl font-bold mb-6 text-foreground">How It Works</h2>
            <div className="space-y-4 text-muted-foreground leading-relaxed">
              <p>
                GlowSips is a reusable pastel straw made from BPA-free food-grade plastic. When cold liquid passes through, it changes color in real time thanks to temperature-reactive polymers. A tiny, removable micro-infuser bead near the tip adds subtle fruit flavors like "raspberry sparkle" or "mango mist."
              </p>
              <p>
                No electronics, no gimmicks—just chemistry, cuteness, and incredible photogenic appeal. Perfect for kids, mocktails, and café culture.
              </p>
            </div>
          </div>

          <div>
            <h2 className="text-3xl font-bold mb-6 text-foreground">Key Features</h2>
            <ul className="space-y-3 text-muted-foreground">
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>Color-changing temperature-reactive technology</span>
              </li>
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>Removable flavor-infuser bead with natural extracts</span>
              </li>
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>Reusable and eco-friendly alternative to disposables</span>
              </li>
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>Available in multiple pastel colors</span>
              </li>
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>High TikTok virality potential with visual transformation</span>
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-3xl font-bold mb-6 text-foreground">Why It Works</h2>
            <p className="text-muted-foreground leading-relaxed">
              GlowSips turns every drink into a tiny moment of wonder. The color shift is incredibly photogenic and shareable on social media. With inexpensive materials and manufacturing, it's positioned perfectly for viral growth. The agents found strongest engagement with parents looking for fun ways to encourage hydration and café-loving millennials seeking Instagram-worthy moments.
            </p>
          </div>
        </div>
      </section>

      {/* Experiment Results */}
      <section id="experiment-results" className="container mx-auto px-6 py-16">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold mb-4 text-foreground">Market Testing Results</h2>
            <p className="text-xl text-muted-foreground">
              Six Feature × Market experiments discovered by autonomous agents
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {adExperiments.map((experiment, index) => (
              <Card key={index} className="overflow-hidden hover:shadow-xl transition-all duration-300">
                <div className="relative aspect-[4/3] overflow-hidden bg-muted">
                  <img 
                    src={experiment.image} 
                    alt={`Ad ${index + 1}: ${experiment.feature} for ${experiment.market}`}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="p-6 space-y-4">
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-semibold text-brand">Feature</span>
                      <span className="text-sm text-foreground">{experiment.feature}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-semibold text-brand">Market</span>
                      <span className="text-sm text-foreground">{experiment.market}</span>
                    </div>
                  </div>
                  <div className="border-t pt-4 space-y-2">
                    <h3 className="font-bold text-foreground">{experiment.headline}</h3>
                    <p className="text-sm text-muted-foreground italic">{experiment.caption}</p>
                  </div>
                  <div className="flex justify-between items-center pt-4 border-t">
                    <div>
                      <div className="text-xs text-muted-foreground">CTR</div>
                      <div className="text-lg font-bold text-brand">{experiment.ctr}</div>
                    </div>
                    <div>
                      <div className="text-xs text-muted-foreground">CPL</div>
                      <div className="text-lg font-bold text-brand">{experiment.cpl}</div>
                    </div>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Winner Highlight */}
      <section className="container mx-auto px-6 py-16 bg-accent/20">
        <div className="max-w-4xl mx-auto text-center space-y-6">
          <h2 className="text-3xl font-bold text-foreground">Winning Variant</h2>
          <p className="text-xl text-muted-foreground">
            The <span className="font-bold text-brand">Aesthetic Instagram × Café Millennials</span> variant achieved the best performance with <span className="font-bold text-brand">3.24% CTR</span> and <span className="font-bold text-brand">$2.38 CPL</span>.
          </p>
          <p className="text-muted-foreground">
            This suggests the strongest product-market fit lies in positioning GlowSips as a must-have aesthetic accessory for café culture and social media enthusiasts.
          </p>
          <Button size="lg" className="bg-brand hover:bg-brand-hover text-white rounded-full px-12 py-6 text-lg">
            Back This Concept
          </Button>
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-6 py-20">
        <div className="max-w-4xl mx-auto text-center space-y-6">
          <h2 className="text-4xl md:text-5xl font-bold text-foreground">
            Help Make GlowSips Real
          </h2>
          <p className="text-xl text-muted-foreground">
            This concept was autonomously discovered and validated. Your backing determines which agent-discovered products get manufactured.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-6">
            <Button size="lg" className="bg-brand hover:bg-brand-hover text-white text-lg px-12 py-7 rounded-full shadow-lg hover:shadow-xl transition-all">
              Pre-Order Now
            </Button>
            <Button size="lg" variant="outline" className="text-lg px-12 py-7 rounded-full transition-all">
              Learn More
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default GlowSips;
