import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import heroProduct from "@/assets/hero-product.jpg";
import ad1 from "@/assets/ad-1.jpg";
import ad2 from "@/assets/ad-2.jpg";
import ad3 from "@/assets/ad-3.jpg";
import ad4 from "@/assets/ad-4.jpg";
import ad5 from "@/assets/ad-5.jpg";
import ad6 from "@/assets/ad-6.jpg";

const MindLinkCompanion = () => {
  const adExperiments = [
    {
      image: ad1,
      feature: "Smart AI Companion",
      market: "Children 3-8",
      headline: "Daily AI mood-pet for young children",
      caption: "Emotion-forward creative with pastel colorway",
      ctr: "2.14%",
      cpl: "$4.05"
    },
    {
      image: ad2,
      feature: "Health Tracking",
      market: "Millennials",
      headline: "Wearable wellness companion",
      caption: "Lifestyle-focused positioning with clean aesthetics",
      ctr: "1.89%",
      cpl: "$4.48"
    },
    {
      image: ad3,
      feature: "Productivity Boost",
      market: "Professionals 25-40",
      headline: "AI-powered focus enhancement",
      caption: "Performance-driven messaging with modern UI",
      ctr: "2.41%",
      cpl: "$3.87"
    },
    {
      image: ad4,
      feature: "Mindfulness Mode",
      market: "Gen Z",
      headline: "Mental wellness tech for students",
      caption: "Authentic, peer-focused creative approach",
      ctr: "1.76%",
      cpl: "$4.85"
    },
    {
      image: ad5,
      feature: "Gaming Integration",
      market: "Gamers 18-35",
      headline: "Level up your real-world stats",
      caption: "Gamification angle with vibrant energy",
      ctr: "2.03%",
      cpl: "$4.21"
    },
    {
      image: ad6,
      feature: "Home Automation",
      market: "Homeowners 30-50",
      headline: "Smart home intelligence hub",
      caption: "Premium, sophisticated positioning",
      ctr: "1.92%",
      cpl: "$4.42"
    }
  ];

  const scrollToResults = () => {
    document.getElementById('experiment-results')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/30">
      {/* Hero Section */}
      <section className="container mx-auto px-6 py-16 md:py-24">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div className="space-y-6">
            <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-foreground">
              MindLink Companion
            </h1>
            <p className="text-xl text-muted-foreground leading-relaxed">
              An AI-powered personal companion that adapts to your emotional state and daily needs, discovered and validated through autonomous market testing.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" className="bg-brand hover:bg-brand-hover text-white text-lg px-8 py-6 rounded-full shadow-lg hover:shadow-xl transition-all">
                Fund This Product
              </Button>
              <Button 
                size="lg" 
                variant="outline"
                onClick={scrollToResults}
                className="text-lg px-8 py-6 rounded-full transition-all"
              >
                View Experiment Results
              </Button>
            </div>
          </div>
          <div className="relative">
            <img 
              src={heroProduct} 
              alt="MindLink Companion Product" 
              className="rounded-3xl shadow-2xl w-full"
            />
            <p className="text-sm text-muted-foreground mt-4 text-center italic">
              Autonomously discovered concept. Image generated by AI.
            </p>
          </div>
        </div>
      </section>

      {/* Section 1: What is MindLink Companion? */}
      <section className="container mx-auto px-6 py-20 max-w-6xl">
        <div className="space-y-6 max-w-4xl mx-auto">
          <h2 className="text-4xl font-bold text-foreground">
            What is MindLink Companion?
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed">
            A hardware-software hybrid that combines AI companionship with biometric sensing to provide personalized emotional support and productivity enhancement. This concept emerged from autonomous agent-driven market research, testing multiple feature sets and audience segments to discover product-market fit before development.
          </p>
          
          <div className="grid md:grid-cols-3 gap-8 pt-8">
            <div className="space-y-3">
              <h3 className="text-xl font-semibold text-foreground">Core Innovation</h3>
              <p className="text-muted-foreground">
                Adaptive AI that learns your patterns and adjusts its responses to match your emotional and cognitive state in real-time.
              </p>
            </div>
            <div className="space-y-3">
              <h3 className="text-xl font-semibold text-foreground">Target Users</h3>
              <p className="text-muted-foreground">
                Professionals, students, and wellness-focused individuals seeking personalized support for productivity and mental wellbeing.
              </p>
            </div>
            <div className="space-y-3">
              <h3 className="text-xl font-semibold text-foreground">Significance</h3>
              <p className="text-muted-foreground">
                First AI companion validated through autonomous market testing, proving demand before a single line of code was written.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Separator */}
      <div className="container mx-auto px-6">
        <div className="h-px bg-border/50 max-w-6xl mx-auto" />
      </div>

      {/* Section 2: How the Agents Tested It */}
      <section id="experiment-results" className="container mx-auto px-6 py-20 max-w-6xl">
        <div className="space-y-6 mb-12 max-w-4xl mx-auto">
          <h2 className="text-4xl font-bold text-foreground">
            How the Agents Tested It
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed">
            Our AI agents autonomously designed, deployed, and analyzed six market experiments across different feature sets and demographics. Each experiment tested a unique value proposition with tailored creative assets and messaging to identify the strongest product-market fit signals.
          </p>
        </div>

        {/* Agent Summary Card */}
        <Card className="p-8 mb-12 bg-accent/30 border-border/50 max-w-4xl mx-auto">
          <h3 className="text-2xl font-semibold mb-6 text-foreground">Agent Testing Summary</h3>
          <div className="grid md:grid-cols-3 gap-6">
            <div>
              <p className="text-sm text-muted-foreground mb-1">Average Cost Per Lead</p>
              <p className="text-3xl font-bold text-foreground">$4.23</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground mb-1">Average Click-Through Rate</p>
              <p className="text-3xl font-bold text-foreground">2.01%</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground mb-1">Total Experiments Run</p>
              <p className="text-3xl font-bold text-foreground">6</p>
            </div>
          </div>
        </Card>
        {/* Ad Experiments Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {adExperiments.map((ad, index) => (
            <Card key={index} className="overflow-hidden hover:shadow-xl transition-shadow">
              <img 
                src={ad.image} 
                alt={ad.headline} 
                className="w-full h-48 object-cover"
              />
              <div className="p-6 space-y-3">
                <div className="flex justify-between items-start gap-2">
                  <div className="text-sm font-medium text-brand">{ad.feature}</div>
                  <div className="text-sm text-muted-foreground">{ad.market}</div>
                </div>
                <h3 className="font-semibold text-foreground leading-snug">{ad.headline}</h3>
                <p className="text-sm text-muted-foreground">{ad.caption}</p>
                <div className="pt-2 border-t border-border/50 flex justify-between items-center">
                  <div>
                    <p className="text-xs text-muted-foreground">CTR</p>
                    <p className="text-sm font-semibold text-foreground">{ad.ctr}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs text-muted-foreground">CPL</p>
                    <p className="text-sm font-semibold text-foreground">{ad.cpl}</p>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </section>

      {/* Separator */}
      <div className="container mx-auto px-6">
        <div className="h-px bg-border/50 max-w-6xl mx-auto" />
      </div>

      {/* Section 3: What We Learned */}
      <section className="container mx-auto px-6 py-20 max-w-6xl">
        <div className="space-y-6 mb-12 max-w-4xl mx-auto">
          <h2 className="text-4xl font-bold text-foreground">
            What We Learned
          </h2>
          <p className="text-lg text-muted-foreground leading-relaxed">
            The autonomous testing revealed clear market preferences and validated specific features with real audience engagement. Here are the key insights that will shape the product roadmap.
          </p>
        </div>

        {/* Key Learnings Grid */}
        <div className="grid md:grid-cols-2 gap-8 mb-12">
          <Card className="p-8 space-y-4 border-2 border-brand/20 bg-brand/5">
            <h3 className="text-xl font-semibold text-foreground">Lowest Cost Per Lead</h3>
            <p className="text-3xl font-bold text-brand">$3.87</p>
            <p className="text-muted-foreground">
              Productivity Boost feature targeting professionals demonstrated the strongest conversion efficiency, indicating high purchase intent.
            </p>
          </Card>

          <Card className="p-8 space-y-4 border-2 border-brand/20 bg-brand/5">
            <h3 className="text-xl font-semibold text-foreground">Hottest Feature</h3>
            <p className="text-3xl font-bold text-brand">Productivity Boost</p>
            <p className="text-muted-foreground">
              2.41% CTR - Performance enhancement messaging resonated strongest, suggesting this should be the lead value proposition.
            </p>
          </Card>

          <Card className="p-8 space-y-4">
            <h3 className="text-xl font-semibold text-foreground">Best Market Segment</h3>
            <p className="text-3xl font-bold text-foreground">Professionals 25-40</p>
            <p className="text-muted-foreground">
              Highest engagement and lowest acquisition cost, indicating this demographic should be the primary launch audience.
            </p>
          </Card>

          <Card className="p-8 space-y-4">
            <h3 className="text-xl font-semibold text-foreground">Strategic Insight</h3>
            <p className="text-muted-foreground">
              AI companions positioned as productivity tools outperform wellness or entertainment angles. The market wants measurable performance gains, not just emotional support.
            </p>
          </Card>
        </div>

        {/* Agent Notes */}
        <Card className="p-8 bg-accent/20 border-border/50 space-y-6">
          <h3 className="text-2xl font-semibold text-foreground">Agent Notes</h3>
          
          <div className="space-y-4">
            <div>
              <h4 className="font-semibold text-foreground mb-2">Surprising Finding</h4>
              <p className="text-muted-foreground">
                Children's market showed strong CTR but low conversion intent signals. This suggests high curiosity but uncertain purchase authority - recommend targeting parents directly rather than children.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-foreground mb-2">Recommended Next Tests</h4>
              <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                <li>Double down on productivity features with enterprise positioning</li>
                <li>Test premium pricing tiers with professionals segment</li>
                <li>Explore B2B channel with wellness benefits angle</li>
              </ul>
            </div>

            <div>
              <h4 className="font-semibold text-foreground mb-2">Roadmap Priority</h4>
              <p className="text-muted-foreground">
                Build MVP focused on productivity tracking, focus enhancement, and performance analytics. Defer gaming and children features to post-launch expansion.
              </p>
            </div>
          </div>
        </Card>
      </section>

      {/* Final CTA */}
      <section className="container mx-auto px-6 py-20 max-w-4xl">
        <Card className="p-12 text-center space-y-6 bg-gradient-to-br from-accent/30 to-accent/10 border-border/50">
          <h2 className="text-3xl font-bold text-foreground">
            Help Bring MindLink Companion to Life
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            The market has spoken. The agents have validated the concept. Now we need your support to build the product that thousands of professionals are waiting for.
          </p>
          <Button 
            size="lg" 
            className="bg-brand hover:bg-brand-hover text-white text-lg px-8 py-6 rounded-full shadow-lg hover:shadow-xl transition-all font-semibold"
          >
            Fund This Product
          </Button>
        </Card>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/50 py-8">
        <div className="container mx-auto px-6 text-center">
          <p className="text-sm text-muted-foreground">
            MindLink Companion - Discovered by AI, Validated by Agents, Built for Humans
          </p>
        </div>
      </footer>
    </div>
  );
};

export default MindLinkCompanion;
