import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import heroProduct from "@/assets/pocket-mellow.jpg";
import ad1 from "@/assets/pocket-mellow-ad-1.png";
import ad2 from "@/assets/pocket-mellow-ad-2.png";
import ad3 from "@/assets/pocket-mellow-ad-3.png";
import ad4 from "@/assets/pocket-mellow-ad-4.png";
import ad5 from "@/assets/pocket-mellow-ad-5.png";
import ad6 from "@/assets/pocket-mellow-ad-6.png";

const PocketMellow = () => {
  const adExperiments = [
    {
      image: ad1,
      feature: "Scent Therapy",
      market: "Students",
      headline: "Study stress relief companion",
      caption: "Academic focus with calming scent angle",
      ctr: "2.68%",
      cpl: "$2.42"
    },
    {
      image: ad2,
      feature: "Lavender Capsule",
      market: "Young Professionals",
      headline: "Desk companion for work stress",
      caption: "Office wellness positioning",
      ctr: "2.31%",
      cpl: "$2.79"
    },
    {
      image: ad3,
      feature: "Collectible Series",
      market: "Gen-Z Women",
      headline: "Kawaii squish collection",
      caption: "Aesthetic collectible angle with pastel colorways",
      ctr: "3.12%",
      cpl: "$2.05"
    },
    {
      image: ad4,
      feature: "Chamomile Calm",
      market: "Anxiety Relief Seekers",
      headline: "Nighttime anxiety companion",
      caption: "Wellness and sleep routine focus",
      ctr: "2.54%",
      cpl: "$2.58"
    },
    {
      image: ad5,
      feature: "Citrus Focus",
      market: "Commuters",
      headline: "Portable stress relief for travel",
      caption: "Urban lifestyle and portability angle",
      ctr: "2.19%",
      cpl: "$2.95"
    },
    {
      image: ad6,
      feature: "Gift Set",
      market: "Gift Buyers",
      headline: "Perfect stress-relief gift",
      caption: "Giftable positioning with premium packaging",
      ctr: "2.47%",
      cpl: "$2.64"
    }
  ];

  const scrollToResults = () => {
    document.getElementById('experiment-results')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/30">
      {/* Hero Section */}
      <section className="container mx-auto px-6 py-16 md:py-24">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div className="space-y-6">
            <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-foreground">
              Pocket Mellow
            </h1>
            <p className="text-xl text-muted-foreground leading-relaxed">
              A tiny pastel squish creature that "inhales your stress" and releases a matching calming scent. Discovered through autonomous market testing with Gen-Z and wellness audiences.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" className="bg-brand hover:bg-brand-hover text-white text-lg px-8 py-6 rounded-full shadow-lg hover:shadow-xl transition-all">
                Fund This Product
              </Button>
              <Button 
                size="lg" 
                variant="outline"
                onClick={scrollToResults}
                className="text-lg px-8 py-6 rounded-full transition-all"
              >
                View Experiment Results
              </Button>
            </div>
          </div>
          <div className="relative">
            <img 
              src={heroProduct} 
              alt="Pocket Mellow Product" 
              className="rounded-3xl shadow-2xl w-full"
            />
            <p className="text-sm text-muted-foreground mt-4 text-center italic">
              Autonomously discovered concept. Image generated by AI.
            </p>
          </div>
        </div>
      </section>

      {/* Product Details */}
      <section className="container mx-auto px-6 py-16 bg-card/50 backdrop-blur">
        <div className="max-w-4xl mx-auto space-y-12">
          <div>
            <h2 className="text-3xl font-bold mb-6 text-foreground">How It Works</h2>
            <div className="space-y-4 text-muted-foreground leading-relaxed">
              <p>
                Pocket Mellow is a soft, hand-sized silicone creature (round, pillowy, Tamagotchi-adjacent) with two removable "mood scent" capsules. When you squeeze it, a small vent releases a gentle scent—lavender for calm, citrus for focus, chamomile for comfort.
              </p>
              <p>
                It's tactile, collectible, and extremely giftable. Zero electronics means ultra-cheap manufacturing while maintaining a premium emotional appeal.
              </p>
            </div>
          </div>

          <div>
            <h2 className="text-3xl font-bold mb-6 text-foreground">Key Features</h2>
            <ul className="space-y-3 text-muted-foreground">
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>Injection-molded silicone body in multiple pastel colorways</span>
              </li>
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>Simple scent pods with diffuser beads and essential oils</span>
              </li>
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>Collectible series with different creatures and scents</span>
              </li>
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>ASMR-friendly squish satisfaction</span>
              </li>
              <li className="flex items-start">
                <span className="text-brand mr-2">→</span>
                <span>Perfect for TikTok virality with adorable aesthetics</span>
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-3xl font-bold mb-6 text-foreground">Why It Works</h2>
            <p className="text-muted-foreground leading-relaxed">
              With a landed cost of just $3-$6 per unit, Pocket Mellow hits the perfect price point for impulse purchases and gift-giving. It looks like a tiny emotional-support creature but is basically a cute squish toy with scent capsules—safe, cheap, and emotionally compelling. The agents found strongest response among students and young professionals seeking micro-stress relief moments.
            </p>
          </div>
        </div>
      </section>

      {/* Experiment Results */}
      <section id="experiment-results" className="container mx-auto px-6 py-16">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold mb-4 text-foreground">Market Testing Results</h2>
            <p className="text-xl text-muted-foreground">
              Six Feature × Market experiments discovered by autonomous agents
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {adExperiments.map((experiment, index) => (
              <Card key={index} className="overflow-hidden hover:shadow-xl transition-all duration-300">
                <div className="relative aspect-[4/3] overflow-hidden bg-muted">
                  <img 
                    src={experiment.image} 
                    alt={`Ad ${index + 1}: ${experiment.feature} for ${experiment.market}`}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="p-6 space-y-4">
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-semibold text-brand">Feature</span>
                      <span className="text-sm text-foreground">{experiment.feature}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-semibold text-brand">Market</span>
                      <span className="text-sm text-foreground">{experiment.market}</span>
                    </div>
                  </div>
                  <div className="border-t pt-4 space-y-2">
                    <h3 className="font-bold text-foreground">{experiment.headline}</h3>
                    <p className="text-sm text-muted-foreground italic">{experiment.caption}</p>
                  </div>
                  <div className="flex justify-between items-center pt-4 border-t">
                    <div>
                      <div className="text-xs text-muted-foreground">CTR</div>
                      <div className="text-lg font-bold text-brand">{experiment.ctr}</div>
                    </div>
                    <div>
                      <div className="text-xs text-muted-foreground">CPL</div>
                      <div className="text-lg font-bold text-brand">{experiment.cpl}</div>
                    </div>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Winner Highlight */}
      <section className="container mx-auto px-6 py-16 bg-accent/20">
        <div className="max-w-4xl mx-auto text-center space-y-6">
          <h2 className="text-3xl font-bold text-foreground">Winning Variant</h2>
          <p className="text-xl text-muted-foreground">
            The <span className="font-bold text-brand">Collectible Series × Gen-Z Women</span> variant achieved the best performance with <span className="font-bold text-brand">3.12% CTR</span> and <span className="font-bold text-brand">$2.05 CPL</span>.
          </p>
          <p className="text-muted-foreground">
            This suggests the strongest product-market fit lies in positioning Pocket Mellow as an aesthetic, collectible series for Gen-Z audiences who value kawaii culture and wellness.
          </p>
          <Button size="lg" className="bg-brand hover:bg-brand-hover text-white rounded-full px-12 py-6 text-lg">
            Back This Concept
          </Button>
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-6 py-20">
        <div className="max-w-4xl mx-auto text-center space-y-6">
          <h2 className="text-4xl md:text-5xl font-bold text-foreground">
            Help Make Pocket Mellow Real
          </h2>
          <p className="text-xl text-muted-foreground">
            This concept was autonomously discovered and validated. Your backing determines which agent-discovered products get manufactured.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-6">
            <Button size="lg" className="bg-brand hover:bg-brand-hover text-white text-lg px-12 py-7 rounded-full shadow-lg hover:shadow-xl transition-all">
              Pre-Order Now
            </Button>
            <Button size="lg" variant="outline" className="text-lg px-12 py-7 rounded-full transition-all">
              Learn More
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default PocketMellow;
