// Freepik text-to-image integration for ad image generation
// Replaces fal.ai with Freepik API

export interface FreepikImage {
  base64: string;
  has_nsfw: boolean;
  url?: string;  // We'll convert base64 to data URL
  width: number;  // Freepik square_1_1 is typically 1024x1024
  height: number;
}

export interface FreepikGenerationResult {
  data: Array<{
    base64: string;
    has_nsfw: boolean;
  }>;
}

/**
 * Generate product/ad images using Freepik text-to-image API
 * @param productName - Name of the product
 * @param productDescription - Description of the product
 * @param audience - Target audience description
 * @param angle - Positioning angle (e.g., "productivity", "aesthetic")
 * @param numImages - Number of images to generate (default: 1)
 * @param apiKey - Freepik API key
 * @returns Array of generated images with base64 data
 */
export async function generateAdImages(options: {
  productName: string;
  productDescription: string;
  audience: string;
  angle: string;
  numImages?: number;
  apiKey: string;
}): Promise<FreepikImage[]> {
  const {
    productName,
    productDescription,
    audience,
    angle,
    numImages = 1,
    apiKey
  } = options;

  // Construct a detailed prompt optimized for ad creatives
  const prompt = [
    `Professional product photography for social media advertisement.`,
    `Product: "${productName}" - ${productDescription}.`,
    `Target audience: ${audience}.`,
    `Marketing angle: ${angle}.`,
    `Style: Clean, modern, eye-catching, Kickstarter-style hero shot.`,
    `Aesthetic: Premium, vibrant, scroll-stopping, optimistic solarpunk vibe.`
  ].join(' ');

  const negative_prompt = 'blurry, low quality, text artifacts, watermark, cluttered, dark, gloomy';

  const requestBody = {
    prompt,
    negative_prompt,
    num_images: numImages,
    image: {
      size: 'square_1_1'  // 1024x1024, perfect for social media
    }
  };

  const response = await fetch('https://api.freepik.com/v1/ai/text-to-image', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-freepik-api-key': apiKey
    },
    body: JSON.stringify(requestBody)
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Freepik API error: ${response.status} - ${errorText}`);
  }

  const result: FreepikGenerationResult = await response.json();

  if (!result.data || result.data.length === 0) {
    throw new Error('No images generated by Freepik');
  }

  // Convert to our standard image format
  return result.data.map(img => ({
    base64: img.base64,
    has_nsfw: img.has_nsfw,
    url: `data:image/png;base64,${img.base64}`,  // Data URL for immediate use
    width: 1024,  // Freepik square_1_1
    height: 1024
  }));
}

/**
 * Generate a single hero image for a product concept
 * Optimized for quick generation with good quality
 */
export async function generateHeroImage(options: {
  productName: string;
  productDescription: string;
  audience: string;
  valueProposition: string;
  apiKey: string;
}): Promise<FreepikImage> {
  const images = await generateAdImages({
    ...options,
    angle: options.valueProposition,
    numImages: 1
  });

  if (images.length === 0) {
    throw new Error('No images generated');
  }

  return images[0];
}

/**
 * Batch generate images for multiple value propositions
 * Useful when creating multiple ad variants at once
 * Note: Freepik API processes sequentially, so this may take time
 */
export async function generateImagesForVariants(options: {
  productName: string;
  productDescription: string;
  audience: string;
  valuePropositions: string[];
  apiKey: string;
}): Promise<Map<string, FreepikImage>> {
  const { productName, productDescription, audience, valuePropositions, apiKey } = options;

  console.log(`🎨 Generating ${valuePropositions.length} images with Freepik...`);

  // Generate images for each value prop sequentially (Freepik rate limits apply)
  const imageMap = new Map<string, FreepikImage>();

  for (let i = 0; i < valuePropositions.length; i++) {
    const valueProp = valuePropositions[i];
    console.log(`   [${i + 1}/${valuePropositions.length}] Generating image for: ${valueProp}`);

    try {
      const image = await generateHeroImage({
        productName,
        productDescription,
        audience,
        valueProposition: valueProp,
        apiKey
      });

      // Check for NSFW content
      if (image.has_nsfw) {
        console.warn(`⚠️  NSFW content detected for "${valueProp}", regenerating...`);
        // Optionally retry or skip
        continue;
      }

      imageMap.set(valueProp, image);
      console.log(`   ✅ Image generated successfully`);

      // Add small delay to respect rate limits
      if (i < valuePropositions.length - 1) {
        await new Promise(resolve => setTimeout(resolve, 1000));  // 1 second delay
      }
    } catch (error) {
      console.error(`   ❌ Failed to generate image for "${valueProp}":`, error);
      // Continue with other images even if one fails
    }
  }

  if (imageMap.size === 0) {
    throw new Error('Failed to generate any images');
  }

  return imageMap;
}

/**
 * Convert base64 image to a public URL (for storage)
 * In production, you'd upload to S3/CloudFlare R2/etc
 * For now, returns data URL
 */
export function convertToPublicUrl(base64: string): string {
  return `data:image/png;base64,${base64}`;
}

/**
 * Estimate Freepik generation cost
 * Freepik pricing varies by plan - check https://www.freepik.com/api/pricing
 */
export function estimateFreepikCost(numImages: number): number {
  // Approximate cost - update based on your plan
  const costPerImage = 0.01;  // ~$0.01 per image (varies by plan)
  return numImages * costPerImage;
}
