/**
 * Generated Raindrop types
 * This file is typically auto-generated by the Raindrop CLI.
 * Run `raindrop dev` or `raindrop build` to generate this file.
 */

export interface Env {
  AI: {
    run(model: string, config: {
      model: string;
      messages: Array<{
        role: "system" | "user" | "assistant";
        content: string;
      }>;
      max_tokens?: number;
      response_format?: { type: string };
    }): Promise<any>;
  };
}
